name: Build all Libraries (Android)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            lib: cimgui
          - os: ubuntu-latest
            arch: x86_64
            lib: cimguizmo
          - os: ubuntu-latest
            arch: x86_64
            lib: cimnodes
          - os: ubuntu-latest
            arch: x86_64
            lib: cimplot
            
    steps:
    - uses: actions/checkout@v4.1.7
      if: matrix.lib != 'cimgui'
      with:
        repository: 'cimgui/cimgui'
        path: 'cimgui'
        submodules: true

    - uses: actions/checkout@v4.1.7
      if: matrix.lib == 'cimgui'
      with:
        repository: 'JunaMeinhold/cimgui'
        path: 'cimgui'
        submodules: true
        
    - uses: actions/checkout@v4.1.7
      if: matrix.lib == 'cimguizmo'
      with:
        repository: 'JunaMeinhold/cimguizmo'
        path: 'cimguizmo'
        submodules: true

    - uses: actions/checkout@v4.1.7
      if: matrix.lib == 'cimnodes'
      with:
        repository: 'JunaMeinhold/cimnodes'
        path: 'cimnodes'
        submodules: true

    - uses: actions/checkout@v4.1.7
      if: matrix.lib == 'cimplot'
      with:
        repository: 'JunaMeinhold/cimplot'
        path: 'cimplot'
        submodules: true

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build
        
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Install Android SDK Command-Line Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O android-sdk-tools.zip
        unzip android-sdk-tools.zip -d tools
        mkdir $HOME/android-sdk/
        mkdir $HOME/android-sdk/cmdline-tools/
        mkdir $HOME/android-sdk/cmdline-tools/latest/
        mv ./tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        chmod +x $HOME/android-sdk/cmdline-tools/latest/bin/*
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        
    - name: Accept Android SDK Licenses
      run: |
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
    - name: Install Specific Android NDK Version 26.3.11579264
      run: |
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.3.11579264"      
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.3.11579264" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/ndk/26.3.11579264" >> $GITHUB_ENV

    - name: Install vcpkg and FreeType
      run: |
        cd ${{ matrix.lib }}
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install freetype --triplet=arm64-android
        ./vcpkg/vcpkg install freetype --triplet=x64-android

    - name: Build for arm64-v8a
      run: |
          cd ${{ matrix.lib }}
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake" \
                -DVCPKG_TARGET_TRIPLET=arm64-android \
                -DIMGUI_WCHAR32=ON \
                -S ./ \
                -B ./build/arm64-v8a
          cmake --build ./build/arm64-v8a  --config Release

    - name: Build for x86_64
      run: |
          cd ${{ matrix.lib }}
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=x86_64 \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake" \
                -DVCPKG_TARGET_TRIPLET=x64-android \
                -DIMGUI_WCHAR32=ON \
                -S ./ \
                -B ./build/x86_64
          cmake --build ./build/x86_64 --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ${{ matrix.lib }}-android-latest-all-artifacts 
        path: |
          ${{ matrix.lib }}/build/arm64-v8a/*.so
          ${{ matrix.lib }}/build/x86_64/*.so
        if-no-files-found: ignore # 'warn' or 'ignore' or 'error'
